import React, { useState } from 'react'
import Card from '../common/Card'
import Select from '../common/Select'
import Input from '../common/Input'
import Button from '../common/Button'
import aiService from '../../services/aiService'
import { useToast } from '../../hooks/useToast'

const CHANNEL_OPTIONS = [
  { value: '',       label: 'Any' },
  { value: 'ONLINE', label: 'Online' },
  { value: 'POS',    label: 'POS' },
  { value: 'ATM',    label: 'ATM' },
  { value: 'MOBILE', label: 'Mobile' },
]

const TYPE_OPTIONS = [
  { value: '',            label: 'Any' },
  { value: 'PURCHASE',    label: 'Purchase' },
  { value: 'REFUND',      label: 'Refund' },
  { value: 'WITHDRAWAL',  label: 'Withdrawal' },
  { value: 'TRANSFER',    label: 'Transfer' },
]

const DummyTransactionGenerator = ({ onGenerated }) => {
  const { addToast } = useToast()
  const [loading, setLoading] = useState(false)
  const [hints, setHints] = useState({ maxAmount: '', channel: '', transactionType: '' })

  const set = (e) => setHints((p) => ({ ...p, [e.target.name]: e.target.value }))

  const generate = async () => {
    setLoading(true)
    try {
      const result = await aiService.generateTransaction({
        maxAmount: hints.maxAmount ? Number(hints.maxAmount) : undefined,
        channel: hints.channel || undefined,
        transactionType: hints.transactionType || undefined,
      })
      onGenerated?.(result)
      addToast('Transaction generated by AI', 'success')
    } catch (err) {
      addToast(err.message, 'error')
    } finally {
      setLoading(false)
    }
  }

  return (
    <Card title="AI Transaction Generator" subtitle="Generate a realistic dummy transaction">
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '0 20px' }}>
        <Input label="Max Amount" name="maxAmount" type="number" placeholder="e.g. 5000"
          value={hints.maxAmount} onChange={set} />
        <Select label="Channel" name="channel" options={CHANNEL_OPTIONS}
          value={hints.channel} onChange={set} />
        <Select label="Transaction Type" name="transactionType" options={TYPE_OPTIONS}
          value={hints.transactionType} onChange={set} />
      </div>
      <Button variant="primary" onClick={generate} loading={loading}>
        Generate Transaction
      </Button>
    </Card>
  )
}

export default DummyTransactionGenerator
